import Head from 'next/head'
import Layout from "@/components/Layout";
import {useAppDispatch} from "@/hooks/useAppDispatch";
import {useEffect} from "react";
import {loginByTokenThunk} from "@/store/auth";

export default function Home() {

    const dispatch = useAppDispatch();

    useEffect(() => {
        const authToken = localStorage.getItem('authToken');
        if (authToken) {
            dispatch(loginByTokenThunk({authToken}))
                .unwrap()
                .catch(e => {});
        }
    }, [])

    return (
        <>
            <Head>
                <title>Music</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="../assets/favicon.ico"/>
            </Head>
            <main>
                <Layout>
                    <div style={{color: 'white'}}>Home</div>
                </Layout>
            </main>
        </>
    )
}
