import Head from 'next/head'
import {songsApi} from "@/api/songs";
import {InferGetStaticPropsType} from "next";
import SongsList from "@/components/songsList/SongsList";

export default function Home({songs, totalCount}: InferGetStaticPropsType<typeof getStaticProps>) {
    console.log('home');
    return (
        <>
            <Head>
                <title>Music</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="../assets/favicon.ico"/>
            </Head>

            <>
                <h1 style={{color: 'white', fontSize: '1.5rem', margin: '15px'}}>Welcome back</h1>
                <h2 style={{color: 'white', margin: '15px'}}>Newest songs</h2>
                <SongsList songs={songs} type={'plate'}/>
            </>

        </>
    )
}

export const getStaticProps = async () => {
    try {
        const {songs, totalCount} = (await songsApi.getAllSongs()).data;
        return {
            props: {
                songs,
                totalCount
            }
        }
    } catch (e) {
        console.log(e);
    }
}
