import Head from 'next/head'
import Layout from "@/components/Layout";
import {songsApi} from "@/api/songs";
import {InferGetStaticPropsType} from "next";
import SongsList from "@/components/songsList/SongsList";

export default function Home({songs}: InferGetStaticPropsType<typeof getStaticProps>) {

    return (
        <>
            <Head>
                <title>Music</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="../assets/favicon.ico"/>
            </Head>
            <main>
                <Layout>
                    <>
                        <div style={{color: 'white'}}>Home</div>
                        <SongsList songs={songs} />
                    </>
                </Layout>
            </main>
        </>
    )
}

export const getStaticProps = async () => {
    try {
        const response = await songsApi.getAllSongs();
        return {
            props: {
                songs: response.data
            }
        }
    } catch(e) {
        console.log(e);
    }
}
